---
title: "CSV Reader"
resource_files:
- .rsconnect_profile
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate) #need to have Python and Conda installed (easiest way is by installing Anaconda, then adding it to your system path)
library(shiny)
library(readxl)
library(tools)
```

```{r include=FALSE}
#run backend python code
source_python("csv_reader.py")

#read in list of vendors and manufacturers
vendors <- read_excel("ActiveVendors.xls")
vendors <- sort(vendors$NAME)   #alphabetize vendors
manufacturers <- read_excel("ActiveMFGs.xls")
manufacturers <- sort(manufacturers$NAME)
```

```{r eruptions, echo=FALSE}
#create 1st input UI pane
inputPanel(
  #file upload interface
  fileInput("file1", "Choose CSV File",
              multiple = FALSE,
              accept = c(".csv")),
  #vendor search interface
  selectizeInput("vendorChoice", "Vendor", vendors, selected = NULL, multiple = FALSE, 
                  options = list(
                  #create placeholder
                    placeholder = 'Select a vendor',
                    onInitialize = I('function() { this.setValue(""); }'))
  ),
  #manufacturer search (is not required to view/download csv and will automatically populate column if in original file)
  selectizeInput("manufacturerChoice", "Manufacturers", manufacturers, selected = NULL, multiple = FALSE, 
                  options = list(
                  #create placeholder
                    placeholder = 'Select a manufacturer:',
                    onInitialize = I('function() { this.setValue(""); }'))
  )
)

#observe changes in user input
observe({
  #run csv reader if .csv file uploaded, vendor selected
  if(!is.null(input$file1)){  
    if(input$vendorChoice != "" && file_ext((input$file1)$datapath) == "csv"){
      inFile <- input$file1
      #error handle python function
      error <<- try(
        #generate .csv template
        csv_avt(inFile$name,inFile$datapath, input$vendorChoice,input$manufacturerChoice)
      )
      #save .csv generated
      mydata <<- read.csv(paste('wwt_',(input$file1)$name, sep = ""), check.names = FALSE)
      #remove temporary file
      file.remove(paste('wwt_',(input$file1)$name, sep = ""))
    }
  }
})

#text output
renderText({
  if(!is.null(input$file1)){
    #handle incorrect file extension
    if(file_ext((input$file1)$datapath) != "csv"){
      "Error: Incorrect file extension"
    }
    #check if a file was generated
    else if(input$vendorChoice != ""){
        if(file_ext((input$file1)$datapath) == "csv"
       && is.null(error)){
          "Template Created"
        }
        else{
          "Invalid Data"
        }
    }
  }
})

#render download button
output$download_button <- renderUI({
  #button rendered if conditions hold
  if(!is.null(input$file1)) {
    if(input$vendorChoice != ""
       && file_ext((input$file1)$datapath) == "csv"){
      if(is.null(error)){
        downloadButton("download", "Download")
      }
    }
  }
})

#render "view csv" button
output$viewCSV <- renderUI({
  #button rendered if conditions hold
  if(!is.null(input$file1)){
    if(input$vendorChoice != ""
      && file_ext((input$file1)$datapath) == "csv"){
        if(is.null(error)){
          actionButton("viewCSV", "View CSV")
        }
    }
  }
})

#handle download button input
output$download <- downloadHandler(
  filename = function() {
    #default file name
    if(!is.null(input$file1)){
      paste('wwt_', (input$file1)$name, sep = "")
    }
  },
  content = function(con) {
    #write downloaded file
    if(!is.null(input$file1) 
       && input$vendorChoice != ""){
          write.csv(mydata, con, na = "", row.names = FALSE)
    }
  }
)

#create 2nd UI input pane
inputPanel(
  uiOutput("viewCSV"),
  uiOutput("download_button")
)

#create data table output
renderDataTable(
  #render datatable if conditions hold
  if(!is.null(input$viewCSV)){
   if(input$viewCSV > 0 && input$vendorChoice != ""
      && file_ext((input$file1)$datapath) == "csv"){
      mydata
   }
  }
)

```
