---
title: "formatDF"
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(openxlsx)
library(plotly)
```

Read in Excel:
```{r}
data <- read.xlsx(here("data", "Backlog_Master_07-12 Forecast.xlsx"),sheet = 4, colNames = TRUE)
```

First row as column names:
```{r}
colnames(data) <- as.character(unlist(data[1,]))
data <- data[-1, ]
```

Remove all commercial events (doesn't work):
```{r}
#data <- data[grepl("Gov", data$`Sales Channel`),]
```

Pie chart by P&L:
```{r}
PLchart1 <- data.frame("Category" = unique(data$`P&L`),GP = aggregate(as.numeric(data$GP), by = list(data$`P&L`), FUN = sum)[,2])
```

```{r}
p1 <- plot_ly(PLchart1, labels = ~Category, values = ~GP, type = 'pie')
p1
```

Pie chart by AM:
```{r}
PLchart2 <- data.frame("Category" = unique(data$`External Rep`),GP = aggregate(as.numeric(data$GP), by = list(data$`External Rep`), FUN = sum)[,2])
```

```{r}
p2 <- plot_ly(PLchart2, labels = ~Category, values = ~GP, type = 'pie')
p2
```

Sunburst plot:
```{r}
data_pos <- data[data$GP > 0,]
chart3_data <- aggregate(as.numeric(data_pos$GP), by = list(data_pos$`P&L`, data_pos$`External Rep`), FUN = sum)

parent_data <- aggregate(chart3_data$x, by = list(chart3_data$Group.1), FUN = sum)
parent_data <- cbind(data.frame(rep("Public", length(parent_data$Group.1))), parent_data)

names(chart3_data) <- names(parent_data)
chart3_data <- rbind(parent_data, chart3_data)
```

```{r}
PLchart3 <- data.frame(
  labels=chart3_data[,2], 
  parents = chart3_data[,1],
  values = chart3_data$x
  )
```

```{r}
p <- plot_ly(
  labels = PLchart3$labels,
  parents = PLchart3$parents,
  values = PLchart3$values,
  type = 'sunburst',
  branchvalues = 'relative'
  )
p
```
